## Training

# Example Predictor: Linear Rollout Predictor

This example contains basic functionality for training and evaluating a linear predictor that rolls out predictions day-by-day.

First, a training data set is created from historical case and npi data.

Second, a linear model is trained to predict future cases from prior case data along with prior and future npi data.
The model is an off-the-shelf sklearn Lasso model, that uses a positive weight constraint to enforce the assumption that increased npis has a negative correlation with future cases.

Third, a sample evaluation set is created, and the predictor is applied to this evaluation set to produce prediction results in the correct format.

In [22]:
import pickle
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split

### Copy the data locally

In [23]:
# Main source for the training data
DATA_URL = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv'
# Local file
DATA_FILE = 'data/OxCGRT_latest.csv'

In [24]:
import os
import urllib.request
if not os.path.exists('data'):
    os.mkdir('data')
# urllib.request.urlretrieve(DATA_URL, DATA_FILE)

In [25]:
# Load historical data from local file
df = pd.read_csv(DATA_FILE, 
                 parse_dates=['Date'],
                 encoding="ISO-8859-1",
                 dtype={"RegionName": str,
                        "RegionCode": str},
                 error_bad_lines=False)

In [26]:
df.columns

Index(['CountryName', 'CountryCode', 'RegionName', 'RegionCode', 'Date',
       'C1_School closing', 'C1_Flag', 'C2_Workplace closing', 'C2_Flag',
       'C3_Cancel public events', 'C3_Flag', 'C4_Restrictions on gatherings',
       'C4_Flag', 'C5_Close public transport', 'C5_Flag',
       'C6_Stay at home requirements', 'C6_Flag',
       'C7_Restrictions on internal movement', 'C7_Flag',
       'C8_International travel controls', 'E1_Income support', 'E1_Flag',
       'E2_Debt/contract relief', 'E3_Fiscal measures',
       'E4_International support', 'H1_Public information campaigns',
       'H1_Flag', 'H2_Testing policy', 'H3_Contact tracing',
       'H4_Emergency investment in healthcare', 'H5_Investment in vaccines',
       'H6_Facial Coverings', 'H6_Flag', 'M1_Wildcard', 'ConfirmedCases',
       'ConfirmedDeaths', 'StringencyIndex', 'StringencyIndexForDisplay',
       'StringencyLegacyIndex', 'StringencyLegacyIndexForDisplay',
       'GovernmentResponseIndex', 'GovernmentResponseIn

In [27]:
# For testing, restrict training data to that before a hypothetical predictor submission date
HYPOTHETICAL_SUBMISSION_DATE = np.datetime64("2020-07-31")
df = df[df.Date <= HYPOTHETICAL_SUBMISSION_DATE]

In [28]:
# Add RegionID column that combines CountryName and RegionName for easier manipulation of data
# GeoID 作为地区的唯一识别号，用于后续的分组中
df['GeoID'] = df['CountryName'] + '__' + df['RegionName'].astype(str)

In [29]:
# Add new cases column
# ConfirmedCases 确诊病例  NewCases 新增病例
df['NewCases'] = df.groupby('GeoID').ConfirmedCases.diff().fillna(0)

In [30]:
# Keep only columns of interest
id_cols = ['CountryName',
           'RegionName',
           'GeoID',
           'Date']
cases_col = ['NewCases']
npi_cols = ['C1_School closing',
            'C2_Workplace closing',
            'C3_Cancel public events',
            'C4_Restrictions on gatherings',
            'C5_Close public transport',
            'C6_Stay at home requirements',
            'C7_Restrictions on internal movement',
            'C8_International travel controls',
            'H1_Public information campaigns',
            'H2_Testing policy',
            'H3_Contact tracing',
            'H6_Facial Coverings']
# 12 列为干预措施 
print(len(npi_cols))
df = df[id_cols + cases_col + npi_cols]

12


In [31]:
# Fill any missing case values by interpolation and setting NaNs to 0
df.update(df.groupby('GeoID').NewCases.apply(
    lambda group: group.interpolate()).fillna(0))

In [32]:
# Fill any missing NPIs by assuming they are the same as previous day
for npi_col in npi_cols:
    df.update(df.groupby('GeoID')[npi_col].ffill().fillna(0))

In [33]:
df

CountryName RegionName        GeoID       Date  NewCases  \
0          Aruba        NaN   Aruba__nan 2020-01-01       0.0   
1          Aruba        NaN   Aruba__nan 2020-01-02       0.0   
2          Aruba        NaN   Aruba__nan 2020-01-03       0.0   
3          Aruba        NaN   Aruba__nan 2020-01-04       0.0   
4          Aruba        NaN   Aruba__nan 2020-01-05       0.0   
...          ...        ...          ...        ...       ...   
7753      Brunei        NaN  Brunei__nan 2020-01-04       0.0   
7754      Brunei        NaN  Brunei__nan 2020-01-05       0.0   
7755      Brunei        NaN  Brunei__nan 2020-01-06       0.0   
7756      Brunei        NaN  Brunei__nan 2020-01-07       0.0   
7757      Brunei        NaN  Brunei__nan 2020-01-08       0.0   

      C1_School closing  C2_Workplace closing  C3_Cancel public events  \
0                   0.0                   0.0                      0.0   
1                   0.0                   0.0                      0.0   
2                   0.0                   0.0                      0.0   
3                   0.0                   0.0                      0.0   
4                   0.0                   0.0                      0.0   
...                 ...                   ...                      ...   
7753                0.0                   0.0                      0.0   
7754                0.0                   0.0                      0.0   
7755                0.0                   0.0                      0.0   
7756                0.0                   0.0                      0.0   
7757                0.0                   0.0                      0.0   

      C4_Restrictions on gatherings  C5_Close public transport  \
0                               0.0                        0.0   
1                               0.0                        0.0   
2                               0.0                        0.0   
3                               0.0                        0.0   
4                               0.0                        0.0   
...                             ...                        ...   
7753                            0.0                        0.0   
7754                            0.0                        0.0   
7755                            0.0                        0.0   
7756                            0.0                        0.0   
7757                            0.0                        0.0   

      C6_Stay at home requirements  C7_Restrictions on internal movement  \
0                              0.0                                   0.0   
1                              0.0                                   0.0   
2                              0.0                                   0.0   
3                              0.0                                   0.0   
4                              0.0                                   0.0   
...                            ...                                   ...   
7753                           0.0                                   0.0   
7754                           0.0                                   0.0   
7755                           0.0                                   0.0   
7756                           0.0                                   0.0   
7757                           0.0                                   0.0   

      C8_International travel controls  H1_Public information campaigns  \
0                                  0.0                              0.0   
1                                  0.0                              0.0   
2                                  0.0                              0.0   
3                                  0.0                              0.0   
4                                  0.0                              0.0   
...                                ...                              ...   
7753                               0.0                              0.0   
7754                         

In [34]:
# Set number of past days to use to make predictions
# 回看的天数，可以自行设置
nb_lookback_days = 30

# Create training data across all countries for predicting one day ahead
# 用过去一个月的数据预测当天的值
X_cols = cases_col + npi_cols
y_col = cases_col
X_samples = []
y_samples = []
geo_ids = df.GeoID.unique()
for g in geo_ids:
    # 筛选出特定区域的数据
    gdf = df[df.GeoID == g]
    all_case_data = np.array(gdf[cases_col])
    all_npi_data = np.array(gdf[npi_cols])

    # Create one sample for each day where we have enough data
    # Each sample consists of cases and npis for previous nb_lookback_days
    # 每个样本包括过去一个月病例和干预措施，相当于当天的预测只参考于过去一个月的数据， K阶马尔可夫
    nb_total_days = len(gdf)
    for d in range(nb_lookback_days, nb_total_days - 1):
        X_cases = all_case_data[d-nb_lookback_days:d]

        # Take negative of npis to support positive
        # weight constraint in Lasso.
        # 取负值，是为了让权重变成正的
        X_npis = -all_npi_data[d - nb_lookback_days:d]
        # X_cases 是一个矩阵，需要拉平为一个向量
        # Flatten all input data so it fits Lasso input format.
        X_sample = np.concatenate([X_cases.flatten(),
                                   X_npis.flatten()])
        y_sample = all_case_data[d + 1]
        X_samples.append(X_sample)
        y_samples.append(y_sample)

X_samples = np.array(X_samples)
y_samples = np.array(y_samples).flatten()
#30 * 1 + 30 *12 前面30列为过去每天的新增病例 后面360列为过去30天的干预措施逐天叠加在一起
print(X_samples, X_samples.shape)
print(y_samples)

[[ 0.  0.  0. ... -0. -0. -0.]
 [ 0.  0.  0. ... -0. -0. -0.]
 [ 0.  0.  0. ... -0. -0. -0.]
 ...
 [ 0.  0.  0. ... -2. -2. -2.]
 [ 0.  0.  0. ... -2. -2. -2.]
 [ 0.  0.  0. ... -2. -2. -2.]] (4550, 390)
[0. 0. 0. ... 0. 0. 0.]


In [35]:
# Helpful function to compute mae
def mae(pred, true):
    return np.mean(np.abs(pred - true))

In [36]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_samples,
                                                    y_samples,
                                                    test_size=0.2,
                                                    random_state=301)

In [37]:
# Create and train Lasso model.
# Set positive=True to enforce assumption that cases are positively correlated
# with future cases and npis are negatively correlated.
model = Lasso(alpha=0.1,
              precompute=True,
              max_iter=10000,
              positive=True,
              selection='random')
# Fit model
model.fit(X_train, y_train)

Lasso(alpha=0.1, max_iter=10000, positive=True, precompute=True,
      selection='random')

In [38]:
# Evaluate model
train_preds = model.predict(X_train)
train_preds = np.maximum(train_preds, 0) # Don't predict negative cases
print('Train MAE:', mae(train_preds, y_train))

test_preds = model.predict(X_test)
test_preds = np.maximum(test_preds, 0) # Don't predict negative cases
print('Test MAE:', mae(test_preds, y_test))

Train MAE: 203.77446801129
Test MAE: 189.2197049937135


In [39]:
# Inspect the learned feature coefficients for the model
# to see what features it's paying attention to.

# Give names to the features
x_col_names = []
for d in range(-nb_lookback_days, 0):
    x_col_names.append('Day ' + str(d) + ' ' + cases_col[0])
for d in range(-nb_lookback_days, 1):
    for col_name in npi_cols:
        x_col_names.append('Day ' + str(d) + ' ' + col_name)

# View non-zero coefficients
for (col, coeff) in zip(x_col_names, list(model.coef_)):
    if coeff != 0.:
        print(col, coeff)
print('Intercept', model.intercept_)

Day -20 NewCases 0.18265761654180926
Day -14 NewCases 0.018997864692999026
Day -13 NewCases 0.05475184732830505
Day -7 NewCases 0.06985426995991362
Day -6 NewCases 0.6179983554596593
Day -5 NewCases 0.08117156478345552
Day -4 NewCases 0.021597025356040002
Day -3 NewCases 0.005484692475913917
Day -1 NewCases 0.08113817543481834
Day -17 H2_Testing policy 16.690233819191402
Day -10 H2_Testing policy 19.381583116170102
Intercept 74.89057336159249


In [40]:
# Save model to file
if not os.path.exists('models'):
    os.mkdir('models')
with open('models/model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

## Evaluation

Now that the predictor has been trained and saved, this section contains the functionality for evaluating it on sample evaluation data.

In [41]:
# Reload the module to get the latest changes
import predict
from importlib import reload
reload(predict)
from predict import predict_df

In [42]:
# 会碰到历史数据很少而不能满足模型需求的情况（冷启动）
%%time
preds_df = predict_df("2020-08-01", "2020-08-31", path_to_ips_file="../../../validation/data/2020-09-30_historical_ip.csv", verbose=True)


Predicting for Aruba__nan
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-01: 127.978388897651
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-02: 152.00418389090316
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-03: 134.58230016960934
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-04: 129.6114640346615
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-05: 137.9135349915164
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-06: 141.0275775376723
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-07: 222.41306761088185
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-08: 249.83127905778446
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-09: 243.5075142658538
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
2020-08-10: 238.61526624749945
X cases shape:  (30,)
X npis shape:  

In [43]:
# Check the predictions
preds_df.head()

CountryName RegionName       Date  PredictedDailyNewCases
213       Aruba        NaN 2020-08-01              127.978389
214       Aruba        NaN 2020-08-02              152.004184
215       Aruba        NaN 2020-08-03              134.582300
216       Aruba        NaN 2020-08-04              129.611464
217       Aruba        NaN 2020-08-05              137.913535

# Validation
This is how the predictor is going to be called during the competition.  
!!! PLEASE DO NOT CHANGE THE API !!!

In [44]:
!python predict.py -s 2020-08-01 -e 2020-08-04 -ip ../../../validation/data/2020-09-30_historical_ip.csv -o predictions/2020-08-01_2020-08-04.csv

Generating predictions from 2020-08-01 to 2020-08-04...
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:

In [45]:
!head predictions/2020-08-01_2020-08-04.csv

'head' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


# Test cases
We can generate a prediction file. Let's validate a few cases...

In [46]:
import os
from covid_xprize.validation.predictor_validation import validate_submission

def validate(start_date, end_date, ip_file, output_file):
    # First, delete any potential old file
    try:
        os.remove(output_file)
    except OSError:
        pass
    
    # Then generate the prediction, calling the official API
    !python predict.py -s {start_date} -e {end_date} -ip {ip_file} -o {output_file}
    
    # And validate it
    errors = validate_submission(start_date, end_date, ip_file, output_file)
    if errors:
        for error in errors:
            print(error)
    else:
        print("All good!")

## 4 days, no gap
- All countries and regions
- Official number of cases is known up to start_date
- Intervention Plans are the official ones

In [47]:
validate(start_date="2020-08-01",
         end_date="2020-08-04",
         ip_file="../../../validation/data/2020-09-30_historical_ip.csv",
         output_file="predictions/val_4_days.csv")

Generating predictions from 2020-08-01 to 2020-08-04...
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30, 1)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:  (390,)
X cases shape:  (30,)
X npis shape:  (30, 12)
X shape:

## 1 month in the future
- 2 countries only
- there's a gap between date of last known number of cases and start_date
- For future dates, Intervention Plans contains scenarios for which predictions are requested to answer the question: what will happen if we apply these plans?

In [48]:
%%time
validate(start_date="2021-01-01",
         end_date="2021-01-31",
         ip_file="../../../validation/data/future_ip.csv",
         output_file="predictions/val_1_month_future.csv")

Generating predictions from 2021-01-01 to 2021-01-31...
历史数据只有0
历史数据只有0


Traceback (most recent call last):
  File "predict.py", line 204, in <module>
    predict(args.start_date, args.end_date, args.ip_file, args.output_file)
  File "predict.py", line 52, in predict
    preds_df = predict_df(start_date, end_date, path_to_ips_file, verbose=False)
  File "predict.py", line 172, in predict_df
    pred_df = pd.concat(geo_pred_dfs)
  File "C:\Users\brook\venvs\covid_env\lib\site-packages\pandas\core\reshape\concat.py", line 284, in concat
    sort=sort,
  File "C:\Users\brook\venvs\covid_env\lib\site-packages\pandas\core\reshape\concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate


FileNotFoundError: [Errno 2] No such file or directory: 'predictions/val_1_month_future.csv'

## 180 days, from a future date, all countries and regions
- Prediction start date is 1 week from now. (i.e. assuming submission date is 1 week from now)  
- Prediction end date is 6 months after start date.  
- Prediction is requested for all available countries and regions.  
- Intervention plan scenario: freeze last known intervention plans for each country and region.  

As the number of cases is not known yet between today and start date, but the model relies on them, the model has to predict them in order to use them.  
This test is the most demanding test. It should take less than 1 hour to generate the prediction file.

### Generate the scenario

In [ ]:
from datetime import datetime, timedelta

start_date = datetime.now() + timedelta(days=7)
start_date_str = start_date.strftime('%Y-%m-%d')
end_date = start_date + timedelta(days=180)
end_date_str = end_date.strftime('%Y-%m-%d')
print(f"Start date: {start_date_str}")
print(f"End date: {end_date_str}")

In [ ]:
from covid_xprize.validation.scenario_generator import get_raw_data, generate_scenario, NPI_COLUMNS
DATA_FILE = 'data/OxCGRT_latest.csv'
latest_df = get_raw_data(DATA_FILE, latest=True)
scenario_df = generate_scenario(start_date_str, end_date_str, latest_df, countries=None, scenario="Freeze")
scenario_file = "predictions/180_days_future_scenario.csv"
scenario_df.to_csv(scenario_file, index=False)
print(f"Saved scenario to {scenario_file}")

### Check it

In [ ]:
%%time
validate(start_date=start_date_str,
         end_date=end_date_str,
         ip_file=scenario_file,
         output_file="predictions/val_6_month_future.csv")